// packages/react-ui/src/views/Home.tsx
import styled from 'styled-components';
import { useQuery } from 'urql';
import { breakpoint } from '@private/design-system/vars';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { SearchSection } from '../components/SearchSection';
import { BundleHero } from '../components/bundle/BundleHero';

const query = `
{
  getTranslations(path:"/", language:"en")
  getBundlesForPath(path:"/") {
    id
    type
    title {
      default
      small
    }
    entities {
      episode {
        id
        title {
          default
          editorial
          live
        }
        subtitle {
          default
          editorial
          live
        }
        image {
          default
          portrait
          promotional
        }
        synopsis {
          small
          editorial
          programmeSmall
          live
        }
        live
        previewId

      }
    }
  }
  }`;

const HomeRoot = styled.div`
  .mobile-only {
    @media (min-width: ${breakpoint.md}) {
      display: none;
    }
  }
`;

function Home() {
  const { i18n, t } = useTranslation();
  const [result] = useQuery({ query });
  const { data, fetching, error } = result;

  i18n.addResourceBundle('en', 'translation', { home: data.getTranslations }, true, true); // awkward i18n merge on render?

  const bundleHero = useMemo(
    () => data.getBundlesForPath?.find((item: IPlayer.Bundle) => item.type === 'hero'),
    [data]
  );
  const bundleRows = useMemo(
    () => data.getBundlesForPath?.filter((item: IPlayer.Bundle) => item.type !== 'hero'),
    [data]
  );

  return (
    <HomeRoot>
      <h1 className="sr-only">{t('home.homepage_title')}</h1>
      <SearchSection className="mobile-only" />
      {bundleHero && <BundleHero bundle={bundleHero} />}
      {/*
    <BundleSection v-for="bundle in bundleRows" :key="bundle.id" :bundle="bundle">
      <BundleRow :bundle="bundle" />
    </BundleSection> */}
    </HomeRoot>
  );
}

export default Home;

// packages/vue-ui/src/views/Home.vue
<template>
  <div>
    <h1 class="sr-only">{{ t('home.homepage_title') }}</h1>
    <SearchSection class="mobile-only" />
    <BundleHero :bundle="bundleHero" />
    <BundleSection v-for="bundle in bundleRows" :key="bundle.id" :bundle="bundle">
      <BundleRow :bundle="bundle" />
    </BundleSection>
  </div>
</template>

<script setup>
import { useQuery } from '@urql/vue';
import { useTranslation } from 'i18next-vue';
import SearchSection from '../components/SearchSection.vue';
import BundleHero from '../components/bundle/BundleHero.vue';
import BundleSection from '../components/bundle/BundleSection.vue';
import BundleRow from '../components/bundle/BundleRow.vue';

const { i18next, t } = useTranslation();

const { data, error } = await useQuery({
  query: `
  {
    getTranslations(path:"/", language:"en")
    getBundlesForPath(path:"/") {
      id
      type
      title {
        default
        small
      }
      entities {
        episode {
          id
          title {
            default
            editorial
            live
          }
          subtitle {
            default
            editorial
            live
          }
          image {
            default
            portrait
            promotional
          }
          synopsis {
            small
            editorial
            programmeSmall
            live
          }
          live
          previewId

        }
      }
    }
    }
  `,
});

const bundleHero = data.value.getBundlesForPath.find((item) => item.type === 'hero');
const bundleRows = data.value.getBundlesForPath.filter((item) => item.type !== 'hero');

const { getTranslations } = data.value;
i18next.addResourceBundle('en', 'translation', { home: getTranslations }, true, true);
</script>

<style lang="scss" scoped>
@media (min-width: $--breakpoint-md) {
  .mobile-only {
    display: none;
  }
}
</style>
