// packages/vue-ui/src/components/Counter.vue
<template>
  <div class="card">
    <button @click="storeCounter.value++">count is {{ value }}</button>
  </div>
</template>

<script setup>
import { storeToRefs } from 'pinia';
import { useStoreCounter } from '../store/counter';

const storeCounter = useStoreCounter();
if (import.meta.env.SSR) {
  storeCounter.value = 3;
}
const { value } = storeToRefs(storeCounter);
</script>

// packages/react-ui/src/components/Counter.tsx
import { useDispatch, useSelector } from 'react-redux';
import { increment, incrementByAmount } from '../store/sliceCounter';
import { RootState } from '../store';

export const Counter = () => {
  const dispatch = useDispatch();

  if (import.meta.env.SSR) {
    dispatch(incrementByAmount(3));
  }
  const count = useSelector((state: RootState) => state.counter.value);

  const onClickIncrement = () => dispatch(increment());

  return (
    <div className="card">
      <button onClick={onClickIncrement}>count is {count}</button>
    </div>
  );
};
