// packages/vue-ui/src/App.vue
<template>
  <div>
    <SkipToContent />
    <Suspense>
      <RouterView v-slot="{ Component }">
        <div>
          <MainNavigation />
          <div id="main-content">
            <component :is="Component" />
          </div>
        </div>
      </RouterView>
    </Suspense>
    <div class="hidden" v-html="iconSprite" />
  </div>
</template>

<script setup>
import SkipToContent from './components/SkipToContent.vue';
import MainNavigation from './components/main-navigation/MainNavigation.vue';
import iconSprite from '@private/design-system/icons.svg?raw';
</script>

// packages/react-ui/src/App.tsx
import { Route, Routes } from 'react-router-dom';
import { MainNavigation } from './components/main-navigation/MainNavgiation';
import { SkipToContent } from './components/SkipToContent';
import Home from './views/Home';
import iconSprite from '@private/design-system/icons.svg?raw';
import '@private/design-system/index.css';

function App() {
  return (
    <main>
      <SkipToContent />
      <MainNavigation />
      <div id="main-content">
        <Routes>
          <Route path="/" element={<Home />} />
        </Routes>
      </div>
      <div className="hidden" dangerouslySetInnerHTML={{ __html: iconSprite }} />
    </main>
  );
}

export default App;
