// packages/vue-ui/src/components/bundle/BundleSection.vue
<template>
  <section class="bundle-section">
    <div class="wrapper">
      <div class="bundle-section__header">
        <h2 class="bundle-section__header__heading font--bold font--size-3">{{ bundle.title.default }}</h2>
        <a
          class="bundle-section__view-all font--bold font--size--1"
          :href="`/iplayer/group/${bundle.id}`"
          :aria-label="`View all programmes from the ${bundle.title.default} group`"
        >
          View all
        </a>
      </div>
    </div>
    <slot />
  </section>
</template>

<script setup>
defineProps({
  bundle: {
    type: Object,
    required: true,
  },
});
</script>

<style scoped lang="scss">
.bundle-section {
  margin-top: calc(var(--size-base-unit) * 6);
  margin-bottom: calc(var(--size-base-unit) * 4);
}
.bundle-section__header {
  display: flex;
  position: relative;
}
.bundle-section__header__heading {
  margin-bottom: calc(var(--size-base-unit) * 4);
  flex: 1;
}

.bundle-section__view-all {
  &:hover,
  &:focus {
    color: var(--color-accent-1);
  }
}
</style>

// packages/react-ui/src/components/bundle/BundleSection.tsx
import styled from 'styled-components';

const BundleSectionRoot = styled.section`
  margin-top: calc(var(--size-base-unit) * 6);
  margin-bottom: calc(var(--size-base-unit) * 4);
`;

const BundleSectionHeader = styled.section`
  display: flex;
  position: relative;
`;
const BundleSectionHeading = styled.h2`
  margin-bottom: calc(var(--size-base-unit) * 4);
  flex: 1;
`;
const BundleSectionViewAll = styled.a`
  &:hover,
  &:focus {
    color: var(--color-accent-1);
  }
`;

interface BundleSectionProps {
  bundle: IPlayer.Bundle;
  children: React.ReactNode;
}
export function BundleSection({ bundle, children }: BundleSectionProps) {
  return (
    <BundleSectionRoot>
      <div className="wrapper">
        <BundleSectionHeader>
          <BundleSectionHeading className="font--bold font--size-3">{bundle.title.default}</BundleSectionHeading>
          <BundleSectionViewAll
            className=" font--bold font--size--1"
            href={`/iplayer/group/${bundle.id}`}
            aria-label={`View all programmes from the ${bundle.title.default} group`}
          >
            View all
          </BundleSectionViewAll>
        </BundleSectionHeader>
      </div>
      {children}
    </BundleSectionRoot>
  );
}
