// packages/vue-ui/src/components-global/ScrollXWithButtons.vue
<template>
  <component :is="is" class="scroller">
    <button
      v-if="canScroll"
      class="scroller__button"
      @click="scrollX(-1)"
      :disabled="arrivedState.left"
      :aria-label="leftAriaLabel"
    >
      <SvgUse href="#gel-icon-previous" />
    </button>
    <div class="scroller__area" ref="scrollerArea">
      <slot />
    </div>
    <button
      v-if="canScroll"
      class="scroller__button"
      @click="scrollX(1)"
      :disabled="arrivedState.right"
      :aria-label="rightAriaLabel"
    >
      <SvgUse href="#gel-icon-next" />
    </button>
  </component>
</template>

<script setup>
import { useScroll, useResizeObserver } from '@vueuse/core';
import { computed, ref } from 'vue';

defineProps({
  is: {
    type: String,
    default: 'div',
  },
  leftAriaLabel: {
    type: String,
    default: 'scroll left',
  },
  rightAriaLabel: {
    type: String,
    default: 'scroll right',
  },
});

const scrollerArea = ref(null);
const { arrivedState } = useScroll(scrollerArea);

const canScroll = ref(true);

useResizeObserver(scrollerArea, (entries) => {
  canScroll.value = scrollerArea.value.scrollWidth > scrollerArea.value.clientWidth;
});

const scrollX = (dir) => {
  const width = scrollerArea.value.offsetWidth * dir;
  scrollerArea.value.scrollLeft += width;
};
</script>

<style scoped lang="scss">
.scroller {
  position: relative;
  display: flex;
}
.scroller__area {
  flex: 1;
  overflow: hidden;
  overflow-x: auto;
}
.scroller__button {
  width: 48px;
  position: relative;
  fill: currentColor;
  display: flex;
  align-items: center;
  justify-content: center;
  &:disabled {
    opacity: 0.4;
  }
  svg {
    width: 12px;
    height: 12px;
  }
}
</style>

// packages/react-ui/src/components/components-global/ScrollXWithButtons.tsx
import { useRef, useState } from 'react';
import styled from 'styled-components';
import useResizeObserver from '@react-hook/resize-observer';
import { useScroll } from 'react-use';
import { SvgUse } from './SvgUse';

const Scroller = styled.div`
  position: relative;
  display: flex;
`;
const ScrollerArea = styled.div`
  flex: 1;
  overflow: hidden;
  overflow-x: auto;
`;
const ScrollerButton = styled.button`
  width: 48px;
  position: relative;
  fill: currentColor;
  display: flex;
  align-items: center;
  justify-content: center;
  &:disabled {
    opacity: 0.4;
  }
  svg {
    width: 12px;
    height: 12px;
  }
`;

interface ScrollXWithButtonsProps {
  leftAriaLabel?: string;
  rightAriaLabel?: string;
}

export function ScrollXWithButtons({
  leftAriaLabel = 'scroll left',
  rightAriaLabel = 'scroll right',
}: ScrollXWithButtonsProps) {
  const scrollerArea = useRef<HTMLDivElement>(null);
  const scrollValues = useScroll(scrollerArea);

  const [canScroll, setCanScroll] = useState(true);

  useResizeObserver(scrollerArea, () => {
    if (scrollerArea.current) {
      setCanScroll(scrollerArea.current.scrollWidth > scrollerArea.current.clientWidth);
    }
  });

  const scrollX = (dir: number) => {
    if (scrollerArea.current) {
      const width = scrollerArea.current.offsetWidth * dir;
      scrollerArea.current.scrollLeft += width;
    }
  };

  return (
    <Scroller>
      {canScroll && (
        <ScrollerButton onClick={() => scrollX(-1)} disabled={scrollValues.x === 0} aria-label={leftAriaLabel}>
          <SvgUse href="#gel-icon-previous" />
        </ScrollerButton>
      )}

      <ScrollerArea ref={scrollerArea}>
        <slot />
      </ScrollerArea>
      {canScroll && (
        <ScrollerButton
          v-if="canScroll"
          onClick={() => scrollX(1)}
          disabled={scrollValues.x === 200000}
          aria-label={rightAriaLabel}
        >
          <SvgUse href="#gel-icon-next" />
        </ScrollerButton>
      )}
    </Scroller>
  );
}
