// packages/vue-ui/src/components/main-navigation/MainNavigationHeader.vue
<template>
  <div class="main-nav__header">
    <div class="main-nav__logo-wrapper">
      <a href="/" aria-label="BBC I Player Home"><Logo class="main-nav__logo" /> </a>
    </div>
    <button
      class="main-nav__mobile-button"
      :class="{ 'main-nav__mobile-button--active': menuOpenProxy }"
      aria-label="Toggle I Player Navigation"
      @click="menuOpenProxy = !menuOpen"
    >
      Menu
    </button>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import Logo from '../../assets/logo.svg';

defineProps({
  menuOpen: {
    type: Boolean,
  },
});

const emit = defineEmits(['update:menuOpen']);

const menuOpenProxy = computed({
  get() {
    return this.menuOpen;
  },
  set(val) {
    emit('update:menuOpen', val);
  },
});
</script>

<style lang="scss" scoped>
.main-nav__header {
  display: flex;
  align-items: center;
  height: 64px;
  padding: 0 calc(var(--size-base-unit) * 4);
}

.main-nav__logo-wrapper {
  flex: 1;
}
.main-nav__logo {
  fill: var(--color-accent-1);
  width: 150px;
}

.main-nav__mobile-button {
  justify-self: flex-end;
  &--active,
  &:hover {
    color: var(--color-accent-1);
  }
}

@media (min-width: $--breakpoint-md) {
  .main-nav__mobile-button {
    display: none;
  }
}
</style>

// packages/react-ui/src/components/main-navigation/MainNavigationHeader.tsx
import { breakpoint } from '@private/design-system/vars';
import styled from 'styled-components';
import Logo from '../../assets/logo.svg?raw';

interface MainNavigationHeaderProps {
  menuOpen: boolean;
  onMenuOpenToggle: Function;
  className?: string;
}

const MainNavigationHeaderRoot = styled.div`
  display: flex;
  align-items: center;
  height: 64px;
  padding: 0 calc(var(--size-base-unit) * 4);
  @media (min-width: ${breakpoint.md}) {
    padding: 0;
  }
`;
const LogoWrapper = styled.div`
  flex: 1;
  svg {
    fill: var(--color-accent-1);
    width: 150px;
  }
`;
const MobileButton = styled.button<{ menuOpen: boolean }>`
  justify-self: flex-end;
  color: ${(props) => (props.menuOpen ? 'var(--color-accent-1)' : 'inherit')};
  &:hover {
    color: var(--color-accent-1);
  }
  @media (min-width: ${breakpoint.md}) {
    display: none;
  }
`;

export function MainNavigationHeader({ menuOpen, onMenuOpenToggle, className }: MainNavigationHeaderProps) {
  return (
    <MainNavigationHeaderRoot className={className}>
      <LogoWrapper>
        <a href="/" aria-label="BBC I Player Home" dangerouslySetInnerHTML={{ __html: Logo }} />
      </LogoWrapper>
      <MobileButton
        menuOpen={menuOpen}
        aria-label="Toggle I Player Navigation"
        onClick={() => onMenuOpenToggle(!menuOpen)}
      >
        Menu
      </MobileButton>
    </MainNavigationHeaderRoot>
  );
}
