// packages/vue-ui/src/components/main-navigation/SubNavigation.vue
<template>
  <nav class="sub-nav" :class="{ 'sub-nav--active': active }">
    <div class="wrapper">
      <ScrollXWithButtons class="scroller">
        <slot name="title" />
        <slot />
      </ScrollXWithButtons>
    </div>
  </nav>
</template>

<script setup>
defineProps({
  active: {
    type: Boolean,
    default: true,
  },
});
</script>

<style scoped lang="scss">
.sub-nav {
  background-color: var(--color-bg-main--active);
  width: 100%;
}

@media (min-width: $--breakpoint-md) {
  .sub-nav {
    display: none;
    position: absolute;
    left: 0;
    top: 100%;
    padding: 0 calc(var(--size-base-unit) * 6);
  }

  .sub-nav--active {
    display: block;
  }
}
</style>

// packages/react-ui/src/components/main-navigation/SubNavigation.tsx
import { breakpoint } from '@private/design-system/vars';
import styled from 'styled-components';
import { ScrollXWithButtons } from '../components-global/ScrollXWithButtons';

interface SubNavigationProps {
  active: boolean;
  title: React.ReactNode;
  children: React.ReactNode;
}

const SubNavigationRoot = styled.nav<{ active: boolean }>`
  background-color: var(--color-bg-main--active);
  width: 100%;

  @media (min-width: ${breakpoint.md}) {
    display: ${(props) => (props.active ? 'block' : 'none')};
    position: absolute;
    left: 0;
    top: 100%;
    padding: 0 calc(var(--size-base-unit) * 6);
  }
`;
export function SubNavigation({ active, title, children }: SubNavigationProps) {
  return (
    <SubNavigationRoot active={active}>
      <div className="wrapper">
        <ScrollXWithButtons>
          {title}
          {children}
        </ScrollXWithButtons>
      </div>
    </SubNavigationRoot>
  );
}
